# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main, cicd ]
  pull_request:
    branches: [ main, cicd ]

permissions:
  contents: read

jobs:
  test_x86-64_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Test with pytest
      run: |
        pytest bootstrap/test/test_x86-64-linux.py
        
  test_x86-16_Dos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        apt install dosbox
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Test with pytest
      run: |
        pytest bootstrap/test/test_x86-16-dos.py
    

