name: Python application

on:
  push:
    branches: [ main, cicd ]
  pull_request:
    branches: [ main, cicd ]

permissions:
  contents: read

jobs:
  test_x86-64_Linux:
    name: Test on x86-64 Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: pytest bootstrap/test/test_x86-64-linux.py
        
  test_x86-16_Dos:
    name: Test on x86-16 DOS (Dosbox)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt install dosbox
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: pytest bootstrap/test/test_x86-16-dos.py
        
  test_avr8_arduino:
    name: Test on avr8 Arduino (QEMU)
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew install qemu
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: pytest bootstrap/test/test_avr8_arduino.py
